version: '3.8'

volumes:
  postgres_data:
  pgadmin_data:

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  web:
    build: ./server
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./server:/app
    expose:
      - 8000
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://pguser:pgpwd@db:5432/pgdb
    depends_on:
      - db
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`django.localhost`)"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpwd
      - POSTGRES_DB=pgdb
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.postgres.loadbalancer.server.port=5432"
    depends_on:
      - traefik

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_LISTEN_PORT=5433
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    expose:
      - 5433
    volumes:
      - pgadmin_data:/pgadmin
    depends_on:
      - db
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=5433"